CREATE TABLE loans (
    loan_id integer PRIMARY KEY,
    loan_name character varying(100),
    original_language character varying(25),
    description character varying(15000),
    description_translated character varying(15000),
    funded_amount numeric(20,2),
    loan_amount numeric(20,2),
    status character varying(100),
    image_id integer,
    video_id character varying(30),
    activity_name character varying(100),
    sector_name character varying(100),
    loan_use character varying(3000),
    country_code character varying(2),
    country_name character varying(100),
    town_name character varying(50),
    currency_policy character varying(100),
    currency_exchange_coverage_rate numeric(3,1),
    currency character varying(3),
    partner_id integer,
    posted_time character varying(29),
    planned_expiration_time character varying(29),
    disburse_time character varying(29),
    raised_time character varying(29),
    lender_term integer,
    num_lenders_total integer,
    num_journal_entries integer,
    num_bulk_entries integer,
    tags character varying(2000),
    borrower_names character varying(1000),
    borrower_genders character varying(500),
    borrower_pictured character varying(500),
    repayment_interval character varying(30),
    distribution_model character varying(30)
);
