CREATE TABLE partners (
    id integer PRIMARY KEY,
    name character varying(98) NOT NULL,
    status character varying(8) NOT NULL,
    rating character varying(9) NOT NULL,
    start_date character varying(20) NOT NULL,
    delinquency_rate character varying(11) NOT NULL,
    default_rate character varying(11) NOT NULL,
    total_amount_raised integer NOT NULL,
    loans_posted integer NOT NULL,
    delinquency_rate_note character varying(614),
    default_rate_note character varying(630),
    portfolio_yield_note character varying(59),
    charges_fees_and_interest character varying(5),
    average_loan_size_percent_per_capita_income character varying(6) NOT NULL,
    loans_at_risk_rate numeric(12,9) NOT NULL,
    currency_exchange_loss_rate character varying(630) NOT NULL,
    url character varying(95),
    portfolio_yield numeric(4,1),
    profitability numeric(6,2)
);
